raw_data_dir: data/raw
processed_data_dir: data/processed
lulc_pattern: LULC_{year}.tif
drivers:
  - elevation.tif
  - slope.tif
  - dist_road.tif
  - dist_water.tif
  - dist_building.tif
  - dist_settlement.tif
  - landuse_mask.tif
